name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          
      - name: List directory contents
        run: ls -la
          
      - name: Install Dependencies
        working-directory: ./exp-days-summary
        run: npm install
          
      - name: Build
        working-directory: ./exp-days-summary
        run: npm run build
        env:
          VITE_TICKET_TAILOR_API_KEY: ${{ secrets.TICKET_TAILOR_API_KEY }}
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./exp-days-summary/dist 